steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['version']
  env: [GOPATH=/gopath']
  volumes:
  - name: 'go'
    path: '/gopath'

- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-d']
  env: [GOPATH=/gopath']
  volumes:
  - name: 'go'
    path: '/gopath'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app','deploy', 'cron.yaml']
  timeout: 600s
  env: ['GOPATH=/gopath']
  volumes:
  - name: 'go'
    path: '/gopath'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app','deploy', 'app.dev.yaml']
  timeout: 600s
  env: ['GOPATH=/gopath']
  volumes:
  - name: 'go'
    path: '/gopath'

